In [23]:
import numpy as np

In [40]:
matrix = [[1,2,3],[1,5,10],[3,5,8]]
matrix_ = [[3,5,7],[2,8,3],[4,5,9]]

In [41]:
print(np.array(matrix))

[[ 1  2  3]
 [ 1  5 10]
 [ 3  5  8]]


In [42]:
print(np.eye(5))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [43]:
print(np.linspace(0,10,20))

[ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]


In [44]:
print(np.arange(0,10,2))

[0 2 4 6 8]


In [45]:
print(np.zeros(5))
print(np.ones(5))
print(np.ones((2,2)))

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[[1. 1.]
 [1. 1.]]


In [46]:
print(np.random.randn(4,4))

[[-0.03843963  1.18442332  0.78612885  0.76908164]
 [ 0.31321516  0.22046842 -2.8178019  -1.09666971]
 [ 2.99986309  0.40696512 -1.05118516 -1.53215686]
 [-0.99752973 -2.09181527 -0.45931431  1.85847448]]


In [57]:
print(np.random.randint(1,7,2))

[5 3]


In [48]:
random_dizi = np.random.randint(0,100,30)

In [49]:
print(random_dizi.max(),random_dizi.argmax())
print(random_dizi.min(),random_dizi.argmin())

99 4
2 20


In [50]:
res = random_dizi.reshape(5,6)

In [51]:
print(random_dizi.reshape(5,6))
print(res.shape)

[[83 22 12 15 99 93]
 [13 98 44 60 96 94]
 [61 38 50 95 16 99]
 [97 91  2 66 51 50]
 [69 31 11 69 27 42]]
(5, 6)


In [52]:
print(random_dizi > 50)
print(random_dizi[random_dizi > 50])

[ True False False False  True  True False  True False  True  True  True
  True False False  True False  True  True  True False  True  True False
  True False False  True False False]
[83 99 93 98 60 96 94 61 95 99 97 91 66 51 69 69]


In [53]:
print(random_dizi)

[83 22 12 15 99 93 13 98 44 60 96 94 61 38 50 95 16 99 97 91  2 66 51 50
 69 31 11 69 27 42]


In [54]:
random_dizi[3:8] = -5
print(random_dizi)

[83 22 12 -5 -5 -5 -5 -5 44 60 96 94 61 38 50 95 16 99 97 91  2 66 51 50
 69 31 11 69 27 42]


In [55]:
print(np.array(matrix) + np.array(matrix_))

[[ 4  7 10]
 [ 3 13 13]
 [ 7 10 17]]
